### ISSUE TITLE
PetIGA-MF

### ISSUE THREAD

**Issue by saidctb** [dalcinl/PetIGA#3]
Is the PetIGA-MF implementation available in this repository? because I can't find an example where it is used

**Comment by dalcinl** [comment]
No, it is not available here. PetIGA-MF is an extension to PetIGA (that is, another library built on top of PetIGA), but it was never made publicly available. If you are interested in using it, please contact me privately to my email.

**Comment by saidctb** [comment]
Thanks, Is there a reason why it was not made public?

**Comment by dalcinl** [comment]
> Thanks, Is there a reason why it was not made public?

Further discussions/comments/questions about PetIGA-MF should be conducted via private channels.
